### PR TITLE
Add bundle for Plone 5.2.x.

### PR DESCRIPTION
**Pull request by thomasmassmann**
Add bundle registration for 5.2.x. This addresses #12.

### CODE REVIEW

**Review by tisto — APPROVED** [review]
Thank you @thomasmassmann! LGTM. Travis is failing but that is unrelated to the PR. Will look into it...

**Comment by thomasmassmann** [comment]
Yeah, this looks like some buildout error.

**Comment by tisto** [comment]
@thomasmassmann merged and released: https://pypi.org/project/kitconcept.dsgvo/1.1.1/#id1

**Comment by thomasmassmann** [comment]
@tisto thanks!

**Pull request merged**
