### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by pbauer**

### CODE REVIEW

**Comment by tisto** [comment]
@pbauer nice. Thanks for working on this!

**Comment by pbauer** [comment]
@tisto merge?

**Comment by tisto** [comment]
@pbauer release? :)

**Comment by tisto** [comment]
@pbauer changelog is missing. Can I add "Python 3 compatibility [pbauer]"?

**Comment by tisto** [comment]
@pbauer ok, seems we need a c.mailchimp release that works with Python 3 first.

**Pull request merged**
